### ISSUE TITLE
visual advertisment

### ISSUE THREAD

**Issue by judovana** [tisnik/vim-weakpoint#1]
General purpose is to upload image for README.md:
Parts of animated gif:
![a](https://user-images.githubusercontent.com/2904395/43991887-2939d98e-9d76-11e8-8132-c618330c80a1.png)
Create single file with presentation
![b](https://user-images.githubusercontent.com/2904395/43991888-295bf988-9d76-11e8-9e35-86740e14bb83.png)
split it to  individual slides and view it
![c](https://user-images.githubusercontent.com/2904395/43991889-297a96c2-9d76-11e8-9887-cd52a16099f3.png)
page up/down navigate to next/previous slide
![d](https://user-images.githubusercontent.com/2904395/43991890-299a2c4e-9d76-11e8-9b2a-1caf3b3ee0f1.png)
![e](https://user-images.githubusercontent.com/2904395/43991891-29b76336-9d76-11e8-8ada-f9bb54344d56.png)
![f](https://user-images.githubusercontent.com/2904395/43991892-29d3925e-9d76-11e8-9cef-a5d1cebcf2a6.png)
![g](https://user-images.githubusercontent.com/2904395/43991893-29f60b5e-9d76-11e8-804c-233ac4bb366a.png)
![h](https://user-images.githubusercontent.com/2904395/43991894-2a3221d4-9d76-11e8-9def-d254d50f3586.png)
![i](https://user-images.githubusercontent.com/2904395/43991895-2aba14e0-9d76-11e8-8a1a-320d0e84ceae.png)
home/end are going to first/last slide
![j](https://user-images.githubusercontent.com/2904395/43991896-2ad7f83e-9d76-11e8-9ba8-420defbe12c8.png)
final animation:
![animation](https://user-images.githubusercontent.com/2904395/43991898-30990754-9d76-11e8-9060-867bb0136c06.gif)

**Comment by judovana** [comment]
At the end, only the gif is used. - see https://github.com/tisnik/vim-weakpoint/pulls from https://github.com/judovana/vim-weakpoint

**Comment by judovana** [comment]
fixing url:
At the end, only the gif is used. - see https://github.com/tisnik/vim-weakpoint/pull/2 from https://github.com/judovana/vim-weakpoint

**Comment by tisnik** [comment]
Looks like this issue has been resolved by @judovana . Thanks again!
